### ISSUE TITLE
Lodash needs to be updated.

### ISSUE THREAD

**Issue by RobertoMachorro** [naz/swagger-express-validator#49]
Based on a [advisory 1065](https://npmjs.com/advisories/1065 ), Lodash needs to be updated. If this is low priority for the project right now, I can fork and fix myself, based on feedback.

**Comment by kibertoad** [comment]
I think I gixed it in master, ee just need to publish.

**Comment by chrkaatz** [comment]
@kibertoad Yes it is fixed already. When are you expecting to publish 1.0.1?

Thanks!
